name: SpringBoot App
description: This repository provides all boilerplate app and deployment code of the SpringBoot Application
branding:
  icon: layers
  color: blue

configs:
  repo-metadata:
      description: 'A SpringBoot web application deployed in Azure App Service'
      topics:
          - java
          - springboot
          - azure-app-service
          - gradle

  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - master
          - releases/*


init:
  uses: "stack-init.yaml"
