name: SpringBoot App
description: This repository provides all boilerplate app and deployment code of the SpringBoot Application
branding:
  icon: package
  color: yellow

inputs:
  - name: AWS_ACCESS_KEY_ID
    description: Enter Your AWS access key id
    is-secret: true
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: Enter the secret access key
    is-secret: true
    required: true
  - name: AWS_REGION_CODE
    description: Enter the Region Code for your ElasticBean Project
    is-secret: true
    required: true
  - name: APPROVING_REVIEWERS_REQUIRED
    description: Number of reviewers required to approve pull requests
    default: 1
    validvalues:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
    
configs:
  repo-metadata:
    parameters:
      description: 'A SpringBoot web application deployed in AWS ElasticBean App Service'
      secrets: 
          - name: AWS_ACCESS_KEY_ID
            value: ${{inputs.AWS_ACCESS_KEY_ID}}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${{inputs.AWS_SECRET_ACCESS_KEY}}
          - name: AWS_REGION_CODE
            value: ${{inputs.AWS_REGION_CODE}}
      topics:
          - java
          - springboot
          - aws-beanstalk-service
          - gradle
  branches:
    - name: master
      parameters:
        allow-force-pushes: false
        allow-deletions: false
        enforce-admins: true
        required-pull-request-reviews:
          dismiss-stale-reviews: true
          require-code-owner-reviews: true
          required-approving-review-count: ${{ inputs.APPROVING_REVIEWERS_REQUIRED }}
  security:
    parameters:
      # Enables dependabot security updates
      automated-security-fixes: true
      # Enables dependabot alerts and the dependency graph for a repository.
      vulnerability-alerts: true
  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - master
          - releases/*
github-apps:
  # Automatically close stale Issues and Pull Requests that tend to accumulate during a project.
  - slug: stale
  - slug: codacy
init:
  uses: "stack-init.yaml"
