name: SpringBoot App
description: This repository provides all boilerplate app and deployment code of the SpringBoot Application
branding:
  icon: package
  color: yellow

inputs:
  - name: AWS_ACCESS_KEY_ID
    description: Enter Your AWS access key id
    is-secret: true
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: Enter the secret access key
    is-secret: true
    required: true
  - name: AWS_REGION_CODE
    description: Enter the Region Code for your ElasticBean Project
    is-secret: false
    required: true
    
configs:
  repo-metadata:
    parameters:
      description: 'A SpringBoot web application deployed in AWS ElasticBean App Service'
      secrets: 
          - name: AWS_ACCESS_KEY_ID
            value: ${{inputs.AWS_ACCESS_KEY_ID}}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${{inputs.AWS_SECRET_ACCESS_KEY}}
      topics:
          - java
          - springboot
          - aws-beanstalk-service
          - gradle
          - mysql
          - azure-sql
  security:
    parameters:
      # Enables dependabot security updates
      automated-security-fixes: true
      # Enables dependabot alerts and the dependency graph for a repository.
      vulnerability-alerts: true
  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - master
          - releases/*
github-apps:
  # Automatically close stale Issues and Pull Requests that tend to accumulate during a project.
  - slug: stale
  # Automated code reviews to help developer ship better software, faster
  - slug: codacy-production
init:
  uses: "stack-init.yaml"
