name: "Setup a spring boot application to Azure App service"

on:
  workflow_dispatch:

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.get-url.outputs.your_site }}
    steps:
      - run: echo "Creating and deploying a spring boot application to azure app service"
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: move the file
        run: |
          mv ./Spring/gradle ./gradle
          mv ./Spring/src ./src
          mv ./Spring/.gitignore ./.gitignore
          mv ./Spring/README.md ./README.md
          mv ./Spring/build.gradle ./build.gradle
          mv ./Spring/gradlew ./gradlew
          mv ./Spring/gradlew.bat ./gradlew.bat
          mv ./Spring/settings.gradle ./settings.gradle
          rm -r ./Spring
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'gradle'
          check-latest: true
          
      - run: ./gradlew build --no-daemon
      
      - name: Configure git
        run: |
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"
            git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
      - name: Commit generated code and initialize workflows
        run: |
          git add .
          git commit -m "Generate framework code and initialize workflows"
          git push 
          
      - name: Gradle Build
        run: gradle build
        
