name: "Setup a spring boot application to AWS Elastic App service"

on:
  workflow_dispatch:

jobs:
  stack-initialization:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - run: echo "Creating and deploying a spring boot application to AWS Elastic app service"
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
       
      # moving the template code to main repository  
      - name: move the file
        run: |
          mv ./Spring/gradle ./gradle
          mv ./Spring/src ./src
          mv ./Spring/.gitignore ./.gitignore
          mv ./Spring/README.md ./README.md
          mv ./Spring/build.gradle ./build.gradle
          mv ./Spring/gradlew ./gradlew
          mv ./Spring/gradlew.bat ./gradlew.bat
          mv ./Spring/settings.gradle ./settings.gradle
          rm -r ./Spring
      
      # Setting up environment
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'gradle'
          check-latest: true
      - run: ./gradlew build --no-daemon
      
      # Git Options
      - name: Configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit generated code and initialize workflows
        run: |
          git add .
          git commit -m "Generate framework code and initialize workflows"
          git push
       
       # Build and Upload the artifact to be used for CI-CD   
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs/
        
